version: "3.0"
name: elastic-search
services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=elasticsearch"
      - "ELASTIC_USERNAME=elasticsearch"
    networks:
      - es
    ports:
      - 9200:9200
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - es
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es: