spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

config:
  elasticsearch:
      uris: localhost:9200
      username: elasticsearch
      password: elasticsearch
      searchContextAlive: 30M